# Eat Safe, Love

## Notebook Set Up

### Importing the JSON data into a MongoDB database using mongoimport command in the terminal
 mongoimport --type json -d uk_food -c establishments --drop --jsonArray establishments.json

In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# confirm that the "uk_food" database is in MongoDB
print(mongo.list_database_names())

['Data', 'admin', 'autosaurus', 'classDB', 'config', 'epa', 'fruits_db', 'gardenDB', 'local', 'met', 'petsitly_marketing', 'uk_food']

In [4]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [5]:
# review the collections in our 'uk_food' database
print(db.list_collection_names())

['establishments']

In [6]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

In [7]:
# Display the total number of documents contained in the establishments collection before using any filter
establishments.count_documents({})

38786

In [8]:
#Display the first document in the results using pprint before filter
pprint(db.establishments.find_one())

{'AddressLine1': 'St Marys Church Of England Primary School',
 'AddressLine2': 'Warren Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'St Marys COE (aided) Primary School',
 'BusinessType': 'School/college/university',
 'BusinessTypeID': 7845,
 'ChangesByServerID': 0,
 'Distance': 4591.871474174837,
 'FHRSID': 289353,
 'LocalAuthorityBusinessID': 'PI/000002468',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CT19 6QH',
 'RatingDate': '2016-09-13T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('658f2f3abeac0549cb15fa7b'),
 'geocode': {'latitude': 51.085797, 'longitude': 1.194762},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/289353',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}

### 1. Which establishments have a hygiene score equal to 20?

In [9]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': {'$eq': 20}}


# Use count_documents to display the number of documents in the result
print("Number of documents in result:", establishments.count_documents(query))

#capture the results to a variable
results = establishments.find(query)

# Display the first document in the results using pprint
print("First Result:")
pprint(results[0])

Number of documents in result: 41
First Result:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('658f2f3abeac0549cb1615ac'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [10]:
# Convert the result to a Pandas DataFrame
establishment_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Number of rows in result: " , len(establishment_df))

Number of rows in result:  41

In [11]:
# Display the first 10 rows of the DataFrame
print("Top 10 establishments having a hygiene score equal to 20 are as following :")
establishment_df.head(10)

Top 10 establishments having a hygiene score equal to 20 are as following :

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,658f2f3abeac0549cb1615ac,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,658f2f3abeac0549cb161930,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,658f2f3abeac0549cb161c35,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,658f2f3abeac0549cb161e26,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,658f2f3abeac0549cb161e38,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,658f2f3abeac0549cb1627d6,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,658f2f3abeac0549cb1629f4,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,658f2f3abeac0549cb163f21,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,http://www.rochford.gov.uk,customerservices@rochford.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,658f2f3abeac0549cb164364,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,http://www.sevenoaks.gov.uk/,environmental.health@sevenoaks.gov.uk,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,658f2f3abeac0549cb164b76,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,http://www.basildon.gov.uk,ehs@basildon.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

In [12]:
# Checking the data types of all fields
sample_document = establishments.find_one()

# Check the data types of fields within the sample document
if sample_document:
    for key, value in sample_document.items():
        data_type = type(value)
        print(f"Field '{key}' has data type: {data_type}")
     
else:
    print("No documents found in the collection.")

Field '_id' has data type: <class 'bson.objectid.ObjectId'>
Field 'FHRSID' has data type: <class 'int'>
Field 'ChangesByServerID' has data type: <class 'int'>
Field 'LocalAuthorityBusinessID' has data type: <class 'str'>
Field 'BusinessName' has data type: <class 'str'>
Field 'BusinessType' has data type: <class 'str'>
Field 'BusinessTypeID' has data type: <class 'int'>
Field 'AddressLine1' has data type: <class 'str'>
Field 'AddressLine2' has data type: <class 'str'>
Field 'AddressLine3' has data type: <class 'str'>
Field 'AddressLine4' has data type: <class 'str'>
Field 'PostCode' has data type: <class 'str'>
Field 'Phone' has data type: <class 'str'>
Field 'RatingValue' has data type: <class 'int'>
Field 'RatingKey' has data type: <class 'str'>
Field 'RatingDate' has data type: <class 'str'>
Field 'LocalAuthorityCode' has data type: <class 'str'>
Field 'LocalAuthorityName' has data type: <class 'str'>
Field 'LocalAuthorityWebSite' has data type: <class 'str'>
Field 'LocalAuthorityEmailAddress' has data type: <class 'str'>
Field 'scores' has data type: <class 'dict'>
Field 'SchemeType' has data type: <class 'str'>
Field 'geocode' has data type: <class 'dict'>
Field 'RightToReply' has data type: <class 'str'>
Field 'Distance' has data type: <class 'float'>
Field 'NewRatingPending' has data type: <class 'bool'>
Field 'meta' has data type: <class 'dict'>
Field 'links' has data type: <class 'list'>

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [13]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query2 = {'LocalAuthorityName': {'$regex': "London",}, 
          'RatingValue': {'$gte': 4}
         }
# Use count_documents to display the number of documents in the result
count2 = establishments.count_documents(query2)
result = establishments.find(query2)
print(f"There are {count2} establishments in London as the Local Authority which have a RatingValue greater than or equal to 4.")

# Display the first document in the results using pprint
pprint(establishments.find_one(query2))

There are 33 establishments in London as the Local Authority which have a RatingValue greater than or equal to 4.
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('658f2f3abeac0549cb162fc9'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [14]:
# Convert the result to a Pandas DataFrame
London_LA_df = pd.DataFrame(result)
# Display the number of rows in the DataFrame
London_LA_df

# Display the number of rows in the DataFrame
print("Number of rows in 'London_LA_df' are : " , len(London_LA_df))
# Display the first 10 rows of the DataFrame
London_LA_df.head(10)

Number of rows in 'London_LA_df' are :  33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,658f2f3abeac0549cb162fc9,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.508551, 'latitude': 51.369321}",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,658f2f3abeac0549cb1632ed,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,658f2f3abeac0549cb163e3c,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.561954, 'latitude': 51.543831}",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,658f2f3abeac0549cb164c3c,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,658f2f3abeac0549cb164c3e,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
5,658f2f3abeac0549cb165344,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
6,658f2f3abeac0549cb167453,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
7,658f2f3abeac0549cb167818,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.048006, 'latitude': 51.503733}",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,658f2f3abeac0549cb167834,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,658f2f3abeac0549cb167835,295107,0,PI/000020749,City Bar & Grill,Restaurant/Cafe/Canteen,1,London City Airport (Airside),London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

In [15]:
# Check that the coordinates and rating value are now numbers
# Find a sample document
sample_document2 = establishments.find_one()

# Check if the "geocode" field exists in the document
if "geocode" in sample_document2:
    # Access data inside the "geocode" dictionary
    longitude_data_type = type(sample_document2["geocode"]["longitude"])
    latitude_data_type = type(sample_document2["geocode"]["latitude"])
    # Print the retrieved data
    print(f"Longitude's datattype is: { longitude_data_type}")
    print(f"Latitude's datatype is : {latitude_data_type}")
else:
    print("Sample document or 'geocode' field not found.")

Longitude's datattype is: <class 'float'>
Latitude's datatype is : <class 'float'>

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [16]:
# Find the latitude and longitude of "Penang Flavours"
query = {'BusinessName': 'Penang Flavours'}

result = establishments.find_one(query)
# Extract latitude and longitude
if "geocode" in result:
    longitude = result["geocode"]["longitude"]
    latitude = result["geocode"]["latitude"]

   # print the retrieved data
    print(f"Longitude for Penang Flavours is: {longitude}")
    print(f"Latitude for Penang Flavours is : {latitude}")
else:
    print("geocode field not found")

Longitude for Penang Flavours is: 0.08384
Latitude for Penang Flavours is : 51.490142

In [17]:
print(longitude)
print(latitude)

0.08384
51.490142

In [18]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude =  51.490142
longitude = 0.08384

query = {
    'RatingValue': {'$eq': 5},
    'geocode.latitude': {'$gte': latitude - degree_search, '$lte': latitude + degree_search},
    'geocode.longitude': {'$gte': longitude - degree_search, '$lte': longitude + degree_search}
}
#Picking only the most important fields to be displayed in the final dataframe
fields = {'geocode': 1, 'BusinessName': 1, 'AddressLine1': 1,'scores.Hygiene': 1, 'RatingValue': 1, 'BusinessType':1}
sort = [('scores.Hygiene', 1)]
limit = 5

# Cast the results as a list and save them to a variable
result = list(establishments.find(query, fields).sort(sort).limit(limit))
         
# Use count_documents to display the number of documents in the result
count3 = establishments.count_documents(query)
print(f"There are {count3} establishments nearest to the new restaurant added, 'Penang Flavours' with a RatingValue of 5, sorted by lowest hygiene score.")


# Pretty print the results
print("Five such establishments are as following: ")
pprint(result)

There are 87 establishments nearest to the new restaurant added, 'Penang Flavours' with a RatingValue of 5, sorted by lowest hygiene score.
Five such establishments are as following:
[{'AddressLine1': '130 - 132 Plumstead High Street',
  'BusinessName': 'Volunteer',
  'BusinessType': 'Pub/bar/nightclub',
  'RatingValue': 5,
  '_id': ObjectId('658f2f3abeac0549cb166e0c'),
  'geocode': {'latitude': 51.4873437, 'longitude': 0.09208},
  'scores': {'Hygiene': 0}},
 {'AddressLine1': '17 Lakedale Road',
  'BusinessName': 'Lumbini Grocery Ltd T/A Al-Iman',
  'BusinessType': 'Retailers - other',
  'RatingValue': 5,
  '_id': ObjectId('658f2f3abeac0549cb166e26'),
  'geocode': {'latitude': 51.4871632, 'longitude': 0.0916256},
  'scores': {'Hygiene': 0}},
 {'AddressLine1': 'Plumstead Manor School Old Mill Road',
  'BusinessName': 'Plumstead Manor Nursery',
  'BusinessType': 'Caring Premises',
  'RatingValue': 5,
  '_id': ObjectId('658f2f3abeac0549cb166e28'),
  'geocode': {'latitude': 51.481517791748, 'longitude': 0.0859939977526665},
  'scores': {'Hygiene': 0}},
 {'AddressLine1': '144 - 146 Plumstead High Street',
  'BusinessName': 'Iceland',
  'BusinessType': 'Retailers - supermarkets/hypermarkets',
  'RatingValue': 5,
  '_id': ObjectId('658f2f3abeac0549cb166de0'),
  'geocode': {'latitude': 51.4871482849121, 'longitude': 0.0924199968576431},
  'scores': {'Hygiene': 0}},
 {'AddressLine1': 'Restaurant And Premises 107A Plumstead High Street',
  'BusinessName': 'Howe and Co Fish and Chips - Van 17',
  'BusinessType': 'Mobile caterer',
  'RatingValue': 5,
  '_id': ObjectId('658f2f3abeac0549cb166def'),
  'geocode': {'latitude': 51.4875335693359, 'longitude': 0.0925370007753372},
  'scores': {'Hygiene': 0}}]

In [19]:
# Convert result to Pandas DataFrame
nearest_to_Penang_df = pd.DataFrame(result)
nearest_to_Penang_df

,_id,BusinessName,BusinessType,AddressLine1,RatingValue,scores,geocode
0,658f2f3abeac0549cb166e0c,Volunteer,Pub/bar/nightclub,130 - 132 Plumstead High Street,5,{'Hygiene': 0},"{'longitude': 0.09208, 'latitude': 51.4873437}"
1,658f2f3abeac0549cb166e26,Lumbini Grocery Ltd T/A Al-Iman,Retailers - other,17 Lakedale Road,5,{'Hygiene': 0},"{'longitude': 0.0916256, 'latitude': 51.4871632}"
2,658f2f3abeac0549cb166e28,Plumstead Manor Nursery,Caring Premises,Plumstead Manor School Old Mill Road,5,{'Hygiene': 0},"{'longitude': 0.0859939977526665, 'latitude': ..."
3,658f2f3abeac0549cb166de0,Iceland,Retailers - supermarkets/hypermarkets,144 - 146 Plumstead High Street,5,{'Hygiene': 0},"{'longitude': 0.0924199968576431, 'latitude': ..."
4,658f2f3abeac0549cb166def,Howe and Co Fish and Chips - Van 17,Mobile caterer,Restaurant And Premises 107A Plumstead High St...,5,{'Hygiene': 0},"{'longitude': 0.0925370007753372, 'latitude': ..."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [20]:
# Checking the data type of Hygiene within scores dictionery
# Find a sample document
sample_document3 = establishments.find_one()

# Check if the "scores" field exists in the document
if "scores" in sample_document3:
    # Access data inside the "scores" dictionary and Hygiene field
    Hygiene_data_type = type(sample_document3["scores"]["Hygiene"])
  
    # Print the retrieved data
    print(f"Hygiene's datattype is: {Hygiene_data_type}")
   
else:
    print("'Scores' and 'Hygiene' fields are not found.")

Hygiene's datattype is: <class 'int'>

In [21]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': {'$eq': 0 }}}

# 2. Groups the matches by Local Authority
group_query = { '$group': {'_id': "$LocalAuthorityName", 'Count': {'$sum':1}}}

# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': {'Count':-1}}

# Put the pipeline together
pipeline = [match_query, group_query, sort_values]

In [22]:
# Run the pipeline through the aggregate method and save the results to a variable
results = list(establishments.aggregate(pipeline))

In [23]:
# Print the number of establishments by Local Authority Name in the result
print("Number of establishments by Local Authority Name in the result: ", len(results))
print("The first ten results are: ")
pprint(results[0:10])

Number of establishments by Local Authority Name in the result:  55
The first ten results are:
[{'Count': 1130, '_id': 'Thanet'},
 {'Count': 882, '_id': 'Greenwich'},
 {'Count': 713, '_id': 'Maidstone'},
 {'Count': 711, '_id': 'Newham'},
 {'Count': 686, '_id': 'Swale'},
 {'Count': 680, '_id': 'Chelmsford'},
 {'Count': 672, '_id': 'Medway'},
 {'Count': 607, '_id': 'Bexley'},
 {'Count': 586, '_id': 'Southend-On-Sea'},
 {'Count': 542, '_id': 'Tendring'}]

In [24]:
# Convert the result to a Pandas DataFrame
result_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Rows in DataFrame: ", len(result_df))

# Display the first 10 rows of the DataFrame
result_df.head(10)

Rows in DataFrame:  55

               _id  Count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542